---
# Copyright 2016 Internet Solutions (Pty) Ltd
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# (c) 2016 Donovan Francesco <donovan.francesco@is.co.za>
# (c) 2016 Paul Stevens <paul.stevens@is.co.za>
- name: Create the prometheus system group
  group:
    name: "{{ prometheus_system_group_name }}"
    state: "present"
    system: "yes"

- name: Create the prometheus system user
  user:
    name: "{{ prometheus_system_user_name }}"
    group: "{{ prometheus_system_group_name }}"
    shell: "{{ prometheus_system_user_shell }}"
    system: "yes"
    createhome: "yes"
    home: "{{ prometheus_system_user_home }}"

- name: Create prometheus dirs
  file:
    path: "{{ item.path }}"
    state: directory
    owner: "{{ item.owner|default(prometheus_system_user_name) }}"
    group: "{{ item.group|default(prometheus_system_group_name) }}"
    mode: "{{ item.mode|default('0755') }}"
  with_items:
    - { path: "/etc/prometheus" }

- name: Create the Alert Manager system group
  group:
    name: "{{ alertmanager_system_group_name }}"
    state: "present"
    system: "yes"
  when:
    - alertmanager_enabled is defined

- name: Create the alertmanager prometheus system user
  user:
    name: "{{ alertmanager_system_user_name }}"
    group: "{{ alertmanager_system_group_name }}"
    groups: "{{ prometheus_system_group_name }}"
    shell: "{{ alertmanager_system_user_shell }}"
    system: "yes"
    createhome: "yes"
    home: "{{ alertmanager_system_user_home }}"
  when:
    - alertmanager_enabled is defined

- name: Create alertmanager dirs
  file:
    path: "{{ item.path }}"
    state: directory
    owner: "{{ item.owner|default(alertmanager_system_user_name) }}"
    group: "{{ item.group|default(alertmanager_system_group_name) }}"
    mode: "{{ item.mode|default('0755') }}"
  with_items:
    - { path: "/etc/alertmanager" }
  when:
    - alertmanager_enabled is defined
